{% set name = "pyslalib" %}
{% set version = "1.0.10" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/pyslalib-{{ version }}.tar.gz
  sha256: da8663bdf9db51e345214a0add057ca7f52f7a892302044e8449b730dac1b085

build:
  skip: true  # [win]
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('fortran') }}
    - meson
    - ninja
    - pkg-config
  host:
    - numpy
    - meson-python >=0.17.1
    - pip
    - python
  run:
    - python

test:
  imports:
    - pyslalib
    - pyslalib.slalib
  commands:
    - pip check
    - python -c "from pyslalib import slalib; assert abs(slalib.sla_airmas(0.5) - 1.1394) < 1e-3"
  requires:
    - pip

about:
  home: https://github.com/scottransom/pyslalib
  summary: f2py and numpy based wrappers for SLALIB
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: gpl-2.0.md

extra:
  recipe-maintainers:
    - ickc
