{% set name = "pyslalib" %}
{% set version = "1.0.9" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 62f1f263d3ffb029bf9c0c0f0688a0ba55be379e7b7df775821e27c2ead7a8b5

build:
  skip: true  # [win]
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('fortran') }}
  host:
    - numpy
    - pip
    - python
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - pyslalib
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/scottransom/pyslalib
  summary: f2py and numpy based wrappers for SLALIB
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: gpl-2.0.md

extra:
  recipe-maintainers:
    - ickc
