{% set name = "pyslalib" %}
{% set version = "1.0.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pySLALIB-{{ version }}.tar.gz
  sha256: b38e71a3011a985ccc1533e4b12bb4fe9b03566adfcc8e4071ed11c5d0660131

build:
  skip: true  # [win]
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
  host:
    - numpy
    - pip
    - python
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - pyslalib
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/scottransom/pyslalib
  summary: f2py and numpy based wrappers for SLALIB
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: gpl-2.0.md

extra:
  recipe-maintainers:
    - ickc
